var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};
$jscomp.polyfill=function(a,b,d,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,f):$jscomp.polyfillUnisolated(a,b,d,f))};$jscomp.polyfillUnisolated=function(a,b,d,f){d=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var c=a[f];c in d||(d[c]={});d=d[c]}a=a[a.length-1];f=d[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,f){var c=a.split(".");a=1===c.length;f=c[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var e=0;e<c.length-1;e++){var l=c[e];l in f||(f[l]={});f=f[l]}c=c[c.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?f[c]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,c,{configurable:!0,writable:!0,value:b}):b!==d&&($jscomp.propertyToPolyfillSymbol[c]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(c):$jscomp.POLYFILL_PREFIX+c,c=$jscomp.propertyToPolyfillSymbol[c],
$jscomp.defineProperty(f,c,{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var d=0,f=function(a){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(a||"")+"_"+d++,a)};return f},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var f=$jscomp.global[b[d]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&$jscomp.defineProperty(f.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof c?a:new c(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){f(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(h){this.asyncThrow_(h)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};c.prototype.createResolveAndReject_=function(){function a(a){return function(e){c||(c=!0,a.call(b,e))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)e.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var e=new b;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(h){c.reject(h)}};c.prototype.then=function(a,b){function e(a,b){return"function"==typeof a?function(b){try{h(a(b))}catch(r){d(r)}}:b}var h,d,f=new c(function(a,b){h=a;d=b});this.callWhenSettled_(e(a,h),e(b,d));return f};
c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?e.asyncExecute(c):this.onSettledCallbacks_.push(c)};c.resolve=d;c.reject=function(a){return new c(function(b,c){c(a)})};c.race=function(a){return new c(function(b,c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())d(f.value).callWhenSettled_(b,
c)})};c.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?d([]):new c(function(a,c){function h(b){return function(c){f[b]=c;k--;0==k&&a(f)}}var f=[],k=0;do f.push(void 0),k++,d(e.value).callWhenSettled_(h(f.length-1),c),e=b.next();while(!e.done)})};return c},"es6","es3");
$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var d=0,f={next:function(){if(d<a.length){var c=d++;return{value:b(c,a[c]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};
$jscomp.construct=function(){function a(){function a(){}new a;Reflect.construct(a,[],function(){});return new a instanceof a}if($jscomp.TRUST_ES6_POLYFILLS&&"undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(a,f,c){a=b(a,f);c&&Reflect.setPrototypeOf(a,c.prototype);return a}}return function(a,b,c){void 0===c&&(c=a);c=$jscomp.objectCreate(c.prototype||Object.prototype);return Function.prototype.apply.call(a,c,b)||c}}();
$jscomp.polyfill("Reflect.construct",function(a){return $jscomp.construct},"es6","es3");$jscomp.findInternal=function(a,b,d){a instanceof String&&(a=String(a));for(var f=a.length,c=0;c<f;c++){var e=a[c];if(b.call(d,e,c,a))return{i:c,v:e}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.polyfill("Object.setPrototypeOf",function(a){return a||$jscomp.setPrototypeOf},"es6","es5");
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,d,f){d=null!=d?d:function(a){return a};var b=[],e="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof e){a=e.call(a);for(var l=0;!(e=a.next()).done;)b.push(d.call(f,e.value,l++))}else for(e=a.length,l=0;l<e;l++)b.push(d.call(f,a[l],l));return b}},"es6","es3");
(function(){function a(b,d,f){function c(g,k){if(!d[g]){if(!b[g]){var h="function"==typeof require&&require;if(!k&&h)return h(g,!0);if(e)return e(g,!0);k=Error("Cannot find module '"+g+"'");throw k.code="MODULE_NOT_FOUND",k;}k=d[g]={exports:{}};b[g][0].call(k.exports,function(a){return c(b[g][1][a]||a)},k,k.exports,a,b,d,f)}return d[g].exports}for(var e="function"==typeof require&&require,l=0;l<f.length;l++)c(f[l]);return c}return a})()({1:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");
Object.defineProperty(d,"__esModule",{value:!0});d.default=function(a,b){var c;fetch("https://flappymillennial2.azure-api.net/flappymillennial/score/".concat(a,"/").concat(b,"/").concat(null!==(c=e)&&void 0!==c?c:"none","/").concat(Date.now())).then(function(a){if(!a.ok)throw Error(a.statusText);return a.json()}).catch(function(){})};var f=b(a("@babel/runtime/regenerator")),c=b(a("@babel/runtime/helpers/asyncToGenerator")),e;(function(){return new Promise(function(a,b){function e(){return d.apply(this,
arguments)}function d(){d=(0,c.default)(f.default.mark(function p(){var a,c,e;return f.default.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return a={excludes:{plugins:!0,localStorage:!0,adBlock:!0,screenResolution:!0,availableScreenResolution:!0,enumerateDevices:!0,pixelRatio:!0,doNotTrack:!0},preprocessor:function(a,b){return"userAgent"===a?(a=new UAParser(b),"".concat(a.getOS().name," :: ").concat(a.getBrowser().name," :: ").concat(a.getEngine().name)):b}},d.prev=1,d.next=4,Fingerprint2.getPromise(a);
case 4:return c=d.sent,e=c.map(function(a){return a.value}),d.abrupt("return",String(Fingerprint2.x64hash128(e.join(""),31)));case 9:d.prev=9,d.t0=d["catch"](1),b(d.t0);case 12:case "end":return d.stop()}},p,null,[[1,9]])}));return d.apply(this,arguments)}window.requestIdleCallback?requestIdleCallback((0,c.default)(f.default.mark(function p(){return f.default.wrap(function(b){for(;;)switch(b.prev=b.next){case 0:return b.t0=a,b.next=3,e();case 3:return b.t1=b.sent,b.abrupt("return",(0,b.t0)(b.t1));
case 5:case "end":return b.stop()}},p)}))):setTimeout((0,c.default)(f.default.mark(function u(){return f.default.wrap(function(b){for(;;)switch(b.prev=b.next){case 0:return b.t0=a,b.next=3,e();case 3:return b.t1=b.sent,b.abrupt("return",(0,b.t0)(b.t1));case 5:case "end":return b.stop()}},u)})),500)})})().then(function(a){return e=a}).catch(function(a){return a})},{"@babel/runtime/helpers/asyncToGenerator":22,"@babel/runtime/helpers/interopRequireDefault":28,"@babel/runtime/regenerator":37}],2:[function(a,
b,d){function f(){(0,c.clearCanvas)();E.nextStep();requestAnimationFrame(f)}d=a("@babel/runtime/helpers/interopRequireDefault");b=d(a("@babel/runtime/helpers/slicedToArray"));var c=a("./library/index.js");a=d(a("./LOGSCORE.js"));var e;window.DEBUGMODE=!1;var l="nirav.com.np"!==window.location.hostname&&"niravko.com"!==window.location.hostname?function(){return!1}:a.default;var g=!0,k=!1,h=0,m=null!==(e=localStorage.getItem("highscore"))&&void 0!==e?e:0,p=window.scenemanager=new c.SceneManager,u=new Audio("assets/score.mp3"),
n=new Audio("assets/dead.mp3");u.load();n.load();var w=new c.StaticText("Score 0",c.cw/2,70,"Economica","#ffffff","bold",60),r=new c.CompositeSpritesheet(new c.FreeDraw(function(a){a.fillStyle="#ffffff";a.lineWidth=3;a.fillRect(-100,-50,200,100);a.strokeRect(-100,-50,200,100)}),new c.StaticText("Score: 0",0,-8,"Economica","#000000","bold",25),new c.StaticText("High Score: "+m,0,25,"Economica","#000000","",20)),v=new c.Character(new c.Kinetics(void 0,c.cw/2,c.ch/2,0,0),void 0,r,0,0,function(){this.hide()}),
B=new c.Character(new c.Kinetics(void 0,0,c.ch-10),new c.Collider("ground",void 0,200,10,-60,0));e=function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:!0,b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:0,e=2<arguments.length?arguments[2]:void 0,d=a?0:c.ch-100,h=a?J:O;h=2===(3<arguments.length&&void 0!==arguments[3]?arguments[3]:1)&&a?F:h;return new c.Character(new c.Kinetics(K(e),c.cw+b+500,d),new c.Collider("pipe",void 0,70,10,0,0),h,70+(a?20:0),70*(a?7:4),e)};var K=
function(a){return function(){g||(this.x-=4,-70>this.x&&(void 0!==a&&a(),this.x=c.cw))}},C=0,x="ZXhhbXM bGF1bmRyeQ  bG92ZQ YWRkaWN0aW9ucw ZGVwcmVzc2lvbg am9ibGVzcw bmV3cw cGFuZGVtaWM cmVjZXNzaW9u ZnV0dXJl Y2xpbWF0ZQ  Z3VuZHJ1aw bHVzdA bG9uZWxpbmVzcw bG9uZ2luZw  cG9saXRpY3M b2JzZXNzaW9ucw bWVkaWE".split(" ");x=x.map(function(a){return window.atob(a)});var A=function(){return x[C++%x.length]};var G=function(a){return C=null!==a&&void 0!==a?a:0};a=["log.png","board.png"].map(function(a){return new c.Spritesheet("assets/".concat(a),
1,{width:0,height:0})});a=(0,b.default)(a,2);var O=a[0],H=a[1];a=[0,0].map(function(){return new c.StaticText(A(),46,472,"Economica","#000000","bold",17)});a=(0,b.default)(a,2);var I=a[0],L=a[1];a=[I,L].map(function(a){return new c.CompositeSpritesheet(H,a)});b=(0,b.default)(a,2);var J=b[0],F=b[1];var t=e(!0,0,function(){P=t.colliders[0].height=300*Math.random()+150;t.spriteOffset.y=P-t.height;I.setText(A())},1);var y=e(!1,0,function(){y.motion.y=P+150},1);var z=e(!0,(c.cw+70)/2,function(){Q=z.colliders[0].height=
300*Math.random()+150;z.spriteOffset.y=Q-z.height;L.setText(A())},2);var D=e(!1,(c.cw+70)/2,function(){D.motion.y=Q+150},2);[y,D].forEach(function(a){return a.registerCollider(new c.Collider("score",void 0,1,150,-70,150))});var P=0,Q=0;t.spriteOffset.x=-10;z.spriteOffset.x=-10;var M=function(){k=g=!0;q.motion.angle<Math.PI/4&&(q.motion.angle+=.1)};var q=new c.Character(new c.Kinetics(function(){if(!g||k)this.y+=S+=.46},140,c.ch/2-20),new c.Collider("flappy",void 0,60,30,30,0),new c.Spritesheet("assets/FlappyMilennialFly.png",
7),120,66,function(){this.runAnimation("base",!0)});var S=0,R=!1;q.jump=function(){var a=this;v.hidden&&k||(v.hidden||p.restart(),g&&(g=!1,this.stopAnimation()),R||(this.runAnimation("base",!1,70),R=!0,S=-8,this.motion.angle=-Math.PI/12,window.setTimeout(function(){return R=!1},120),window.setTimeout(function(){a.motion.angle=0},200)))};q.collideActions.ground=function(){M();n.play();q.motion.angle=Math.PI/4;q.paused=!0;v.unhide();l(h,m)};q.collideActions.pipe=M;var N=!1;q.collideActions.score=function(){N||
(N=!0,T(++h),u.play())};q.collideActions.NO_COLLISIONS=function(){N&&(N=!1)};[B.colliders[0],y.colliders[1],D.colliders[1],t.colliders[0],z.colliders[0],y.colliders[0],D.colliders[0]].forEach(function(a){return q.registerCollisionWith(a)});var T=function(a){var b;h=a;w.setText(a);r.sprites[1].setText("Score: "+a);m=null!==(b=localStorage.getItem("highscore"))&&void 0!==b?b:0;h>m&&(localStorage.setItem("highscore",m=h),r.sprites[2].setText("High Score: "+m))};b=new c.Event;b.subscribe(q,[{code:"Space",
cb:q.jump}]);q.registerEvent(b);c.canvas.addEventListener("touchstart",function(a){return q.jump()});window.onload=function(){return f()};b=new c.Camera(c.cw,c.ch,0,0);var E=new c.Scene(b);p.register("level",E);E.startingCondition=function(){g=!0;k=!1;q.motion.angle=0;T(0);G();[B,t,y,z,D,w,q,v].forEach(function(a){return E.register(a)})};var U=0;b=function(){return k?[U,0]:[++U,0]};[new c.Background(["assets/grassy/layers_fullcolor/sky_fc.png"],0,200,void 0,0),new c.Background(["assets/grassy/layers_fullcolor/far_mountains_fc.png"],
0,0,b,.05),new c.Background(["assets/grassy/layers_fullcolor/grassy_mountains_fc.png"],0,0,b,.2),new c.Background(["assets/grassy/layers_fullcolor/clouds_mid_fc.png"],0,0,b,.3),new c.Background(["assets/grassy/layers_fullcolor/hill.png"],50,0,b,.5)].forEach(function(a){return E.registerBG(a)});E.registerFG(new c.Background(["assets/grassy/layers_fullcolor/clouds_front_t_fc.png"],0,0,b,1.3));E.startingCondition()},{"./LOGSCORE.js":1,"./library/index.js":14,"@babel/runtime/helpers/interopRequireDefault":28,
"@babel/runtime/helpers/slicedToArray":34}],3:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,"__esModule",{value:!0});d.default=void 0;var f=b(a("@babel/runtime/helpers/classCallCheck")),c=b(a("@babel/runtime/helpers/defineProperty")),e=a("./canvas.js");d.default=function m(a,b,d){var h=this,k=3<arguments.length&&void 0!==arguments[3]?arguments[3]:"",g=4<arguments.length?arguments[4]:void 0;(0,f.default)(this,m);(0,c.default)(this,"text","");(0,c.default)(this,
"font","");(0,c.default)(this,"color","");(0,c.default)(this,"property","");(0,c.default)(this,"size",void 0);(0,c.default)(this,"maxWidth",500);(0,c.default)(this,"draw",function(a,b){var c,d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:0,f=3<arguments.length&&void 0!==arguments[3]?arguments[3]:1,p=4<arguments.length&&void 0!==arguments[4]?arguments[4]:1,k=5<arguments.length&&void 0!==arguments[5]?arguments[5]:void 0,m=6<arguments.length?arguments[6]:void 0;m=null!==(c=m)&&void 0!==c?c:
h.maxWidth;void 0===k&&(k=void 0===h.size?20:h.size);e.cc.save();e.cc.translate(a,b);0!==d&&e.cc.rotate(d);1!==f&&1!==p&&e.cc.scale(f,p);e.cc.font=h.property+" "+k+"px "+h.font;e.cc.fillStyle=h.color;e.cc.fillText(h.text,-e.cc.measureText(h.text).width/2,0,m);e.cc.restore()});this.text=a;this.font=b;d&&(this.color=d);this.property=k;this.size=g}},{"./canvas.js":7,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/interopRequireDefault":28}],
4:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,"__esModule",{value:!0});d.StaticTextGeneratorGenerator=function(a,b,c,e){return function(d,h,f){return new k(d,h,f,a,b,c,e)}};d.StaticText=d.StaticImage=void 0;var f=b(a("@babel/runtime/helpers/classCallCheck")),c=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),l=b(a("./spritesheet.js")),g=b(a("./SimpleText.js"));a=function(){function a(b,c,d){var h=3<arguments.length&&
void 0!==arguments[3]?arguments[3]:void 0,p=4<arguments.length&&void 0!==arguments[4]?arguments[4]:void 0;(0,f.default)(this,a);(0,e.default)(this,"img",l.default);(0,e.default)(this,"x",void 0);(0,e.default)(this,"y",void 0);(0,e.default)(this,"height",void 0);(0,e.default)(this,"width",void 0);void 0!==b&&(this.img=new l.default(b),this.x=c,this.y=d,this.height=h,this.width=p)}(0,c.default)(a,[{key:"draw",value:function(a,b){this.img.draw(this.x+a,this.y+b,0,1,1,this.width,this.height)}}]);return a}();
d.StaticImage=a;var k=function(){function a(b,c,d,h,k){var p=5<arguments.length&&void 0!==arguments[5]?arguments[5]:"",m=6<arguments.length?arguments[6]:void 0;(0,f.default)(this,a);(0,e.default)(this,"text",g.default);(0,e.default)(this,"x",void 0);(0,e.default)(this,"y",void 0);(0,e.default)(this,"font",void 0);(0,e.default)(this,"text",g.default);this.text=new g.default(b,h,k,p,m);this.x=c;this.y=d}(0,c.default)(a,[{key:"init",value:function(){}},{key:"nextStep",value:function(){}},{key:"dismantle",
value:function(){}},{key:"setText",value:function(a){this.text.text=a}},{key:"setProperty",value:function(a){this.text.property=a}},{key:"draw",value:function(a,b){this.text.draw(this.x+a,this.y+b)}}]);return a}();d.StaticText=k},{"./SimpleText.js":3,"./spritesheet.js":18,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/interopRequireDefault":28}],5:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");
Object.defineProperty(d,"__esModule",{value:!0});d.default=void 0;var f=b(a("@babel/runtime/helpers/slicedToArray")),c=b(a("@babel/runtime/helpers/classCallCheck")),e=b(a("@babel/runtime/helpers/createClass")),l=b(a("@babel/runtime/helpers/defineProperty")),g=a("./canvas.js");a=function(){function a(b,e,d,f,k){var h=this;(0,c.default)(this,a);(0,l.default)(this,"images",[]);(0,l.default)(this,"bgStack",[]);(0,l.default)(this,"parallaxFactor",.2);(0,l.default)(this,"scale",1);(0,l.default)(this,"debugmode",
!1);(0,l.default)(this,"nImgsLoaded",0);(0,l.default)(this,"allImgsLoaded",!1);(0,l.default)(this,"indexRight",0);(0,l.default)(this,"indexLeft",0);void 0!==b&&(b.forEach(function(a){var b=new Image;b.src=a;b.onload=function(){h.nImgsLoaded+=1;h.nImgsLoaded===h.images.length&&(h.allImgsLoaded=!0)};h.images.push(b)}),this.x=void 0===e?0:e,this.y=void 0===d?0:d,this.motionFunc=void 0===f?void 0:f,void 0!==k&&(this.parallaxFactor=k))}(0,e.default)(a,[{key:"populateBgStack",value:function(){var a=0;if(this.allImgsLoaded)for(var b=
0;b<=g.cw;){var c=this.images[a++%this.images.length];this.bgStack.push({img:c,x:b,y:"whatever"});b+=c.width*this.scale}}},{key:"setScale",value:function(){this.scale=0<arguments.length&&void 0!==arguments[0]?arguments[0]:1;this.populateBgStack()}},{key:"nextIndex",value:function(a){if(void 0===a)return 0;if("left"===a)return 0>this.indexLeft&&(this.indexLeft=0),this.indexLeft++%this.images.length;if("right"===a)return 0>this.indexRight&&(this.indexRight=0),this.indexRight++%this.images.length}},
{key:"decIndex",value:function(a){if(void 0===a)return 0;"left"===a?(--this.indexLeft,0>this.indexLeft&&(this.indexLeft=0)):"right"===a&&(--this.indexRight,0>this.indexRight&&(this.indexRight=0))}},{key:"draw",value:function(a,b){var c=this,e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:2;if(void 0!==this.motionFunc){var d=this.motionFunc();d=(0,f.default)(d,2);a=d[0];b=d[1]}e!==this.scale&&this.setScale(e);0===this.bgStack.length&&this.populateBgStack();a*=this.parallaxFactor;b*=this.parallaxFactor;
d=this.bgStack[this.bgStack.length-1];var h=d.img.width*e;d.x+h<a+g.cw?this.bgStack.push({img:this.images[this.nextIndex("right")],x:d.x+h,y:"whatever"}):d.x>a+g.cw&&(this.decIndex("right"),this.bgStack.pop());d=this.bgStack[0];h=d.img.width*e;a>d.x+h?(this.decIndex("left"),this.bgStack.shift()):d.x>a&&this.bgStack.unshift({img:this.images[this.nextIndex("left")],x:d.x-h,y:"dontcare"});this.bgStack.forEach(function(b){var d=b.img;void 0!==d&&(g.cc.save(),g.cc.translate(b.x-a-c.x,g.ch-d.height*e-c.y),
g.cc.scale(e,e),g.cc.drawImage(d,0,0,d.width,d.height),g.cc.restore())})}}]);return a}();d.default=a},{"./canvas.js":7,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/interopRequireDefault":28,"@babel/runtime/helpers/slicedToArray":34}],6:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,"__esModule",{value:!0});d.default=void 0;var f=b(a("@babel/runtime/helpers/classCallCheck")),
c=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),l=b(a("./character.js"));a=function(){function a(b,c){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:0,h=3<arguments.length&&void 0!==arguments[3]?arguments[3]:0,k=4<arguments.length&&void 0!==arguments[4]?arguments[4]:void 0,g=5<arguments.length&&void 0!==arguments[5]?arguments[5]:void 0,w=6<arguments.length&&void 0!==arguments[6]?arguments[6]:0;(0,f.default)(this,a);(0,e.default)(this,"elements",
[]);(0,e.default)(this,"offsetX",0);(0,e.default)(this,"offsetY",0);(0,e.default)(this,"frameWidth",void 0);(0,e.default)(this,"frameHeight",void 0);(0,e.default)(this,"follow",l.default);(0,e.default)(this,"followSpeed",void 0);(0,e.default)(this,"followDirection","xy");(0,e.default)(this,"cameraMotion",void 0);(0,e.default)(this,"x",void 0);(0,e.default)(this,"y",void 0);(0,e.default)(this,"backgrounds",[]);(0,e.default)(this,"foregrounds",[]);this.frameWidth=b;this.frameHeight=c;this.follow=k;
this.x=d;this.y=h;this.cameraMotion=g;this.followSpeed=w;this.init=function(){this.x=d;this.y=h}}(0,c.default)(a,[{key:"dismantle",value:function(){this.elements=[]}},{key:"registerChar",value:function(a){this.elements.push(a);return this.elements.length-1}},{key:"unregisterChar",value:function(a){delete this.elements[a]}},{key:"withinBounds",value:function(a){return!0}},{key:"renderFrame",value:function(){var a=this;this.cameraMotion&&this.cameraMotion();if(this.follow){if("x"===this.followDirection||
"xy"===this.followDirection)this.follow.motion.x-this.x>2*this.frameWidth/3?this.x=0<this.followSpeed?this.x+this.followSpeed:this.x+this.follow.motion.vx:this.follow.motion.x-this.x<this.frameWidth/3&&(this.x=0<this.followSpeed?this.x-this.followSpeed:this.x+this.follow.motion.vx);if("y"===this.followDirection||"xy"===this.followDirection)this.follow.motion.y-this.y>2/3*this.frameHeight?this.y=0<this.followSpeed?this.y+this.followSpeed:this.y+this.follow.motion.vy:this.follow.motion.y-this.y<this.frameHeight/
3&&(this.y=0<this.followSpeed?this.y-this.followSpeed:this.y+this.follow.motion.vy)}this.backgrounds.forEach(function(b){b.draw(a.x,a.y)});this.elements.forEach(function(b){a.withinBounds(b.motion)&&(b===a.follow?(b.draw(-a.x,-a.y),DEBUGMODE&&(b.hasDebugAnnotations()&&b.debugDrawAnnotations(-a.x,-a.y),b.debugDrawCollider(-a.x,-a.y))):(b.draw(-a.x,-a.y),DEBUGMODE&&(b.hasDebugAnnotations&&b.hasDebugAnnotations()&&b.debugDrawAnnotations(-a.x,-a.y),b.debugDrawCollider&&b.debugDrawCollider(-a.x,-a.y))))});
this.foregrounds.forEach(function(b){b.draw(a.x,a.y)})}},{key:"registerBG",value:function(a){this.backgrounds.push(a)}},{key:"registerFG",value:function(a){this.foregrounds.push(a)}}]);return a}();d.default=a},{"./character.js":8,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/interopRequireDefault":28}],7:[function(a,b,d){Object.defineProperty(d,"__esModule",{value:!0});d.clearCanvas=function(){var a=
0<arguments.length&&void 0!==arguments[0]?arguments[0]:"#000";f.save();f.fillStyle=a;f.fillRect(0,0,c,e);f.restore()};d.ch=d.cw=d.cc=d.canvas=void 0;a=document.getElementById("game");d.canvas=a;var f=a.getContext("2d");d.cc=f;f.imageSmoothingEnabled=!1;var c=a.clientWidth;d.cw=c;var e=a.clientHeight;d.ch=e},{}],8:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,"__esModule",{value:!0});d.default=void 0;var f=b(a("@babel/runtime/helpers/classCallCheck")),
c=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),l=a("./kinetics.js"),g=a("./canvas.js");b(a("./spritesheet.js"));a=function(){function a(b,c,d){var h=3<arguments.length&&void 0!==arguments[3]?arguments[3]:void 0,g=4<arguments.length&&void 0!==arguments[4]?arguments[4]:void 0,p=5<arguments.length&&void 0!==arguments[5]?arguments[5]:void 0,k=6<arguments.length&&void 0!==arguments[6]?arguments[6]:void 0;(0,f.default)(this,a);(0,e.default)(this,"width",void 0);
(0,e.default)(this,"height",void 0);(0,e.default)(this,"colliders",[]);(0,e.default)(this,"collidesWith",[]);(0,e.default)(this,"collideActions",[]);(0,e.default)(this,"animations",[]);(0,e.default)(this,"spriteOffset",{x:0,y:0});(0,e.default)(this,"baseAnimation",void 0);(0,e.default)(this,"motion",l.Kinetics);(0,e.default)(this,"initFn",void 0);(0,e.default)(this,"paused",!0);(0,e.default)(this,"hidden",!1);(0,e.default)(this,"keyboard",void 0);(0,e.default)(this,"startingVariables",void 0);(0,
e.default)(this,"animationRunning",!1);(0,e.default)(this,"debugAnnotations",[]);c&&(c.motion=b);this.motion=b;this.colliders[0]=c;this.baseAnimation=d;this.animations[0]=d;this.animations.base=d;this.width=h;this.height=g;void 0!==p&&(this.initFn=p.bind(this));void 0!==k&&(this.disinitFn=k.bind(this));this.startingVariables={x:b.x,y:b.y}}(0,c.default)(a,[{key:"registerCollider",value:function(a){a&&void 0!==a&&(a.motion=this.motion,this.colliders.push(a))}},{key:"registerCollisionWith",value:function(a){this.collidesWith.push(a)}},
{key:"registerAnimation",value:function(a,b){this.animations[a]=b}}]);(0,c.default)(a,[{key:"clone",value:function(){return new a(this.motion.clone(),this.colliders[0].clone(),this.baseAnimation.clone(),this.width,this.height)}},{key:"init",value:function(){this.unpause();this.unhide();this.motion.x=this.startingVariables.x;this.motion.y=this.startingVariables.y;void 0!==this.initFn&&this.initFn()}},{key:"dismantle",value:function(){this.pause();void 0!==this.disinitFn&&this.disinitFn()}},{key:"nextStep",
value:function(){this.paused||(this.motion.computePhysics(),this.checkCollisions())}},{key:"pause",value:function(){this.paused=!0;void 0!==this.keyboard&&this.keyboard.disarm()}},{key:"unpause",value:function(){this.paused=!1;void 0!==this.keyboard&&this.keyboard.arm()}},{key:"hide",value:function(){this.hidden=!0}},{key:"unhide",value:function(){this.hidden=!1}},{key:"draw",value:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:0,b=1<arguments.length&&void 0!==arguments[1]?
arguments[1]:0;this.hidden||void 0===this.baseAnimation||this.baseAnimation.draw(this.motion.x+a+this.spriteOffset.x,this.motion.y+b+this.spriteOffset.y,this.motion.angle,this.motion.xdirection,this.motion.ydirection,this.width,this.height)}},{key:"checkCollisions",value:function(){var a=this,b=!0;this.colliders.forEach(function(c){a.collidesWith.forEach(function(d){c.isColliding(d)&&(b=!1,void 0!==a.collideActions[d.name]&&a.collideActions[d.name].bind(a)(c.collisionDirection(d),c,d))})});b&&this.collideActions.NO_COLLISIONS&&
this.collideActions.NO_COLLISIONS.bind(this)()}},{key:"runAnimation",value:function(){var a=this,b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"base",c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:100,d=3<arguments.length?arguments[3]:void 0,e=4<arguments.length&&void 0!==arguments[4]?arguments[4]:!0;!1===(1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1)?(this.baseAnimation.disengage(),this.baseAnimation=this.animations[b],this.baseAnimation.engage(),this.baseAnimation.startAnimOneShot(c,
function(){e&&a.baseAnimation.resetFrame();d&&d.bind(a)()})):(this.baseAnimation.disengage(),this.baseAnimation=this.animations[b],this.baseAnimation.engage(),this.baseAnimation.startAnim(c))}},{key:"stopAnimation",value:function(){this.baseAnimation.stopAnim()}},{key:"setSprite",value:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"base";this.baseAnimation.resetFrame();this.baseAnimation=this.animations[a]}},{key:"registerEvent",value:function(a){this.keyboard=a;this.paused||
this.keyboard.arm()}},{key:"debugDrawCollider",value:function(a,b){var c=this;this.colliders.forEach(function(d){void 0!==d&&(g.cc.save(),g.cc.fillStyle="rgba(0,0,0,0)",g.cc.lineWidth="1",g.cc.strokeStyle="white",g.cc.strokeRect(c.motion.x-d.offsetX+a,c.motion.y-d.offsetY+b,d.width,d.height),g.cc.fillStyle="white",g.cc.fillRect(c.motion.x+a,c.motion.y+b,3,3),g.cc.fillStyle="red",g.cc.fillRect(c.motion.x+a,c.motion.y+b+3,3,3),g.cc.restore())})}},{key:"registerDebugAnnotation",value:function(a){return this.debugAnnotations.push(a)-
1}},{key:"unregisterDebugAnnotation",value:function(a){void 0!==a&&delete this.debugAnnotations[a]}},{key:"hasDebugAnnotations",value:function(){return 0!==this.debugAnnotations.filter(function(a){return a}).length}},{key:"debugDrawAnnotations",value:function(a,b){g.cc.save();g.cc.strokeStyle="white";g.cc.fillStyle="white";this.debugAnnotations.forEach(function(c){"line"===c.type?(g.cc.beginPath(),g.cc.moveTo(c.x1+a,c.y1+b),g.cc.lineTo(c.x2+a,c.y2+b),g.cc.stroke()):"text"===c.type&&g.cc.fillText(c.text,
c.x+a,c.y+b)});g.cc.restore()}}]);return a}();d.default=a},{"./canvas.js":7,"./kinetics.js":15,"./spritesheet.js":18,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/interopRequireDefault":28}],9:[function(a,b,d){function f(a,b){var c=Object.keys(a);if(Object.getOwnPropertySymbols){var d=Object.getOwnPropertySymbols(a);b&&(d=d.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable}));
c.push.apply(c,d)}return c}function c(a){for(var b=1;b<arguments.length;b++){var c=null!=arguments[b]?arguments[b]:{};b%2?f(Object(c),!0).forEach(function(b){(0,g.default)(a,b,c[b])}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(c)):f(Object(c)).forEach(function(b){Object.defineProperty(a,b,Object.getOwnPropertyDescriptor(c,b))})}return a}b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,"__esModule",{value:!0});d.default=void 0;
var e=b(a("@babel/runtime/helpers/classCallCheck")),l=b(a("@babel/runtime/helpers/createClass")),g=b(a("@babel/runtime/helpers/defineProperty")),k=a("./kinetics.js"),h=a("./constants.js");a=function(){function a(b,c,d,f,h,l){(0,e.default)(this,a);(0,g.default)(this,"name",String);(0,g.default)(this,"motion",k.Kinetics);(0,g.default)(this,"width",void 0);(0,g.default)(this,"height",void 0);(0,g.default)(this,"offsetX",void 0);(0,g.default)(this,"offsetY",void 0);this.motion=c;this.width=d;this.height=
f;this.offsetX=h;this.offsetY=l;this.name=b}(0,l.default)(a,[{key:"clone",value:function(a){void 0===a&&(a=this.motion.clone());return c(c({},this),{},{motion:a})}},{key:"isColliding",value:function(a){var b=this.motion.x-this.offsetX,c=this.motion.y-this.offsetY,d=this.width,e=this.height,f=a.motion.x-a.offsetX,g=a.motion.y-a.offsetY,h=a.height;return b<f+a.width&&b+d>f&&c<g+h&&c+e>g?!0:!1}},{key:"collisionDirection",value:function(a){var b=this.motion.x-this.offsetX,c=this.motion.y-this.offsetY,
d=this.width,e=this.height,f=a.motion.x-a.offsetX,g=a.motion.y-a.offsetY,h=a.width,k=[];k[0]=Math.abs(c-(g+a.height));k[1]=Math.abs(b+d-f);k[2]=Math.abs(c+e-g);k[3]=Math.abs(b-(f+h));var l=Math.min.apply(Math,k),p=0;k.forEach(function(a,b){a==l&&(p=b)});return p}},{key:"resolveCollisionLand",value:function(a,b){void 0===b&&(b=this.collisionDirection(a));2==b?(this.motion.ay=0,this.motion.vy=0,this.motion.setY(a.motion.y-a.offsetY-(this.height-this.offsetY))):0==b?(this.motion.vy=0,this.motion.setY(a.motion.y-
a.offsetY+a.height+this.offsetY)):3===b?this.motion.setX(a.motion.x-a.offsetX+a.width+this.offsetX):1==b&&this.motion.setX(a.motion.x-a.offsetX-this.offsetX)}},{key:"resolveCollisionHard",value:function(a,b){void 0===b&&(b=this.collisionDirection(a));2==b?(this.motion.ay=0,this.motion.vy=0,this.motion.setY(a.motion.y-a.offsetY-(this.height-this.offsetY))):0==b?(this.motion.ay=h.physics.gravity,this.motion.vy=0,this.motion.setY(a.motion.y-a.offsetY+a.height+this.offsetY)):3===b?(this.motion.vx=0,this.motion.ax=
1,this.motion.setX(a.motion.x-a.offsetX+a.width+this.offsetX)):1==b&&(this.motion.vx=0,this.motion.ax=-1,this.motion.setX(a.motion.x-a.offsetX-this.offsetX))}},{key:"resolveCollisionMoving",value:function(a){0==a.collisionDirection(this)?(this.motion.vx=1.25*a.motion.xdirection,this.motion.y=a.motion.y-this.height+14):2==a.collisionDirection(this)?(this.motion.ay=h.physics.gravity,this.motion.vy=0,this.motion.y+=4):1==a.collisionDirection(this)?this.motion.x=a.motion.x+a.width+6:3==a.collisionDirection(this)&&
(this.motion.x=a.motion.x-this.width)}}]);return a}();d.default=a},{"./constants.js":10,"./kinetics.js":15,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/interopRequireDefault":28}],10:[function(a,b,d){Object.defineProperty(d,"__esModule",{value:!0});d.physics={gravity:.06,decayMotion:.79};d.frameRateMs=75},{}],11:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,
"__esModule",{value:!0});d.default=void 0;var f=b(a("@babel/runtime/helpers/classCallCheck")),c=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),l=b(a("./character.js"));a=function(){function a(b,c){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:1E3,g=3<arguments.length&&void 0!==arguments[3]?arguments[3]:{min:1,max:3},h=4<arguments.length&&void 0!==arguments[4]?arguments[4]:{x:30,y:30};(0,f.default)(this,a);(0,e.default)(this,"motion",void 0);
(0,e.default)(this,"particle",void 0);(0,e.default)(this,"decayTime",void 0);(0,e.default)(this,"curParticles",[]);this.motion=b;this.particle=c;this.decayTime=d;this.range=g;this.locationRange=h}(0,c.default)(a,[{key:"emit",value:function(){var a=this,b=this.range,c=this.locationRange;b=Math.floor(Math.random()*(b.max-b.min))+b.min;for(var d=function(b){var d=Math.floor(Math.random()*c.x*2)-c.x,e=Math.floor(Math.random()*c.y*2)-c.y;b=a.particle[Math.floor(a.particle.length*Math.random())];void 0===
b&&(console.log("the random indexing is producing out of range values prolly"),b=a.particle[0]);var f=b,g=f.collider,h=f.sprite,k=f.width,m=f.height,n=f.init;b=f.afterFn;f=f.motion.clone();f.x=a.motion.x+d;f.y=a.motion.y+e;d=void 0;void 0!==g&&(d=g.clone(f));e=h.clone();k=new l.default(f,d,e,k,m,n);var u=window.sceneManager.curScene.register(k);b&&b(k);setTimeout(function(){window.sceneManager.curScene.unregister(u)},a.decayTime)},e=0;e<b;e++)d(e)}},{key:"dismantle",value:function(){}}]);return a}();
d.default=a},{"./character.js":8,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/interopRequireDefault":28}],12:[function(a,b,d){function f(a){var b=c();return function(){var c=(0,g.default)(a);if(b){var d=(0,g.default)(this).constructor;c=Reflect.construct(c,arguments,d)}else c=c.apply(this,arguments);return(0,l.default)(this,c)}}function c(){if("undefined"===typeof Reflect||!Reflect.construct||
Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Date.prototype.toString.call(Reflect.construct(Date,[],function(){})),!0}catch(p){return!1}}b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,"__esModule",{value:!0});d.default=void 0;var e=b(a("@babel/runtime/helpers/inherits")),l=b(a("@babel/runtime/helpers/possibleConstructorReturn")),g=b(a("@babel/runtime/helpers/getPrototypeOf")),k=b(a("@babel/runtime/helpers/classCallCheck")),h=b(a("@babel/runtime/helpers/createClass")),
m=b(a("@babel/runtime/helpers/defineProperty"));a=function(){function a(){var b=this;(0,k.default)(this,a);(0,m.default)(this,"subscribersKey",[]);(0,m.default)(this,"keyUpQueue",[]);(0,m.default)(this,"subscribersMouse",[]);(0,m.default)(this,"codesAlreadyRegistered",[]);(0,m.default)(this,"keyDown",function(a){b.subscribersKey.forEach(function(c){c.keyEvent.forEach(function(d){if(d.code==a.code){a.preventDefault();var e=d.cb.bind(c.character)();void 0!==e&&void 0===b.codesAlreadyRegistered.find(function(a){return a===
d.code})&&(b.keyUpQueue.push({code:d.code,cb:e,character:c.character}),b.codesAlreadyRegistered.push(d.code))}})})}.bind(this));(0,m.default)(this,"keyUp",function(a){b.keyUpQueue.forEach(function(c,d,e){a.code===c.code&&void 0!==c.cb&&(c.cb.bind(c.character)(a),e.splice(d,1),b.codesAlreadyRegistered=b.codesAlreadyRegistered.filter(function(b){return b!==a.code}))})}.bind(this));(0,m.default)(this,"mouseMove",function(a){b.subscribersMouse.filter(function(a){return"move"==a.event}).forEach(function(b){return b.fn.bind(b.character)(a)})}.bind(this))}
(0,h.default)(a,[{key:"arm",value:function(){window.addEventListener("keydown",this.keyDown);window.addEventListener("keyup",this.keyUp);window.addEventListener("mousemove",this.mouseMove)}},{key:"disarm",value:function(){window.removeEventListener("keydown",this.keyDown);window.removeEventListener("keyup",this.keyUp);window.removeEventListener("mousemove",this.mouseMove)}},{key:"subscribe",value:function(a){this.subscribersKey.push({character:a,keyEvent:1<arguments.length&&void 0!==arguments[1]?
arguments[1]:[]})}},{key:"subscribeMouse",value:function(a,b){var c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:"move";"move"===c&&this.subscribersMouse.push({character:a,fn:b,event:c})}}]);return a}();d.default=a;(function(a){function b(){(0,k.default)(this,b);return c.apply(this,arguments)}(0,e.default)(b,a);var c=f(b);return b})(a);(function(a){function b(){(0,k.default)(this,b);return c.apply(this,arguments)}(0,e.default)(b,a);var c=f(b);return b})(a)},{"@babel/runtime/helpers/classCallCheck":23,
"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/getPrototypeOf":26,"@babel/runtime/helpers/inherits":27,"@babel/runtime/helpers/interopRequireDefault":28,"@babel/runtime/helpers/possibleConstructorReturn":32}],13:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,"__esModule",{value:!0});d.default=void 0;var f=b(a("@babel/runtime/helpers/classCallCheck")),c=b(a("@babel/runtime/helpers/createClass")),
e=b(a("@babel/runtime/helpers/defineProperty")),l=a("./canvas.js");a=function(){function a(b){var c=this;(0,f.default)(this,a);(0,e.default)(this,"draw",function(a,b){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:0,e=3<arguments.length&&void 0!==arguments[3]?arguments[3]:1,f=4<arguments.length&&void 0!==arguments[4]?arguments[4]:1;void 0!==c.drawFn&&(l.cc.save(),l.cc.translate(a,b),0!==d&&l.cc.rotate(d),1!==e&&1!==f&&l.cc.scale(e,f),c.drawFn(l.cc),l.cc.restore())});this.drawFn=b}(0,
c.default)(a,[{key:"clone",value:function(){return new a(this.drawFn)}},{key:"engage",value:function(){}},{key:"disengage",value:function(){}},{key:"startAnim",value:function(){}}]);return a}();d.default=a},{"./canvas.js":7,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/interopRequireDefault":28}],14:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireWildcard");var f=a("@babel/runtime/helpers/interopRequireDefault");
Object.defineProperty(d,"__esModule",{value:!0});Object.defineProperty(d,"Background",{enumerable:!0,get:function(){return c.default}});Object.defineProperty(d,"Camera",{enumerable:!0,get:function(){return e.default}});Object.defineProperty(d,"canvas",{enumerable:!0,get:function(){return l.canvas}});Object.defineProperty(d,"cc",{enumerable:!0,get:function(){return l.cc}});Object.defineProperty(d,"cw",{enumerable:!0,get:function(){return l.cw}});Object.defineProperty(d,"ch",{enumerable:!0,get:function(){return l.ch}});
Object.defineProperty(d,"clearCanvas",{enumerable:!0,get:function(){return l.clearCanvas}});Object.defineProperty(d,"Character",{enumerable:!0,get:function(){return g.default}});Object.defineProperty(d,"Collider",{enumerable:!0,get:function(){return k.default}});Object.defineProperty(d,"Emitter",{enumerable:!0,get:function(){return h.default}});Object.defineProperty(d,"Event",{enumerable:!0,get:function(){return m.default}});Object.defineProperty(d,"FreeDraw",{enumerable:!0,get:function(){return p.default}});
Object.defineProperty(d,"Kinetics",{enumerable:!0,get:function(){return u.Kinetics}});Object.defineProperty(d,"PhysicsKinetics",{enumerable:!0,get:function(){return u.PhysicsKinetics}});Object.defineProperty(d,"PhysicsKineticsLand",{enumerable:!0,get:function(){return u.PhysicsKineticsLand}});Object.defineProperty(d,"Scene",{enumerable:!0,get:function(){return n.default}});Object.defineProperty(d,"SceneManager",{enumerable:!0,get:function(){return w.default}});Object.defineProperty(d,"SimpleText",
{enumerable:!0,get:function(){return r.default}});Object.defineProperty(d,"Spritesheet",{enumerable:!0,get:function(){return v.default}});Object.defineProperty(d,"CompositeSpritesheet",{enumerable:!0,get:function(){return v.CompositeSpritesheet}});Object.defineProperty(d,"StaticImage",{enumerable:!0,get:function(){return B.StaticImage}});Object.defineProperty(d,"StaticText",{enumerable:!0,get:function(){return B.StaticText}});Object.defineProperty(d,"StaticTextGeneratorGenerator",{enumerable:!0,get:function(){return B.StaticTextGeneratorGenerator}});
var c=f(a("./background.js")),e=f(a("./camera.js")),l=a("./canvas.js"),g=f(a("./character.js")),k=f(a("./collider.js")),h=f(a("./emitter.js")),m=f(a("./events.js")),p=f(a("./freeDraw.js")),u=a("./kinetics.js"),n=f(a("./scene.js")),w=f(a("./sceneManager.js")),r=f(a("./SimpleText.js")),v=b(a("./spritesheet.js")),B=a("./StaticRenderables.js")},{"./SimpleText.js":3,"./StaticRenderables.js":4,"./background.js":5,"./camera.js":6,"./canvas.js":7,"./character.js":8,"./collider.js":9,"./emitter.js":11,"./events.js":12,
"./freeDraw.js":13,"./kinetics.js":15,"./scene.js":16,"./sceneManager.js":17,"./spritesheet.js":18,"@babel/runtime/helpers/interopRequireDefault":28,"@babel/runtime/helpers/interopRequireWildcard":29}],15:[function(a,b,d){function f(a){var b=c();return function(){var c=(0,m.default)(a);if(b){var d=(0,m.default)(this).constructor;c=Reflect.construct(c,arguments,d)}else c=c.apply(this,arguments);return(0,h.default)(this,c)}}function c(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;
if("function"===typeof Proxy)return!0;try{return Date.prototype.toString.call(Reflect.construct(Date,[],function(){})),!0}catch(B){return!1}}function e(a,b){var c=Object.keys(a);if(Object.getOwnPropertySymbols){var d=Object.getOwnPropertySymbols(a);b&&(d=d.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable}));c.push.apply(c,d)}return c}function l(a){for(var b=1;b<arguments.length;b++){var c=null!=arguments[b]?arguments[b]:{};b%2?e(Object(c),!0).forEach(function(b){(0,n.default)(a,
b,c[b])}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(c)):e(Object(c)).forEach(function(b){Object.defineProperty(a,b,Object.getOwnPropertyDescriptor(c,b))})}return a}b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,"__esModule",{value:!0});d.PhysicsKineticsLand=d.PhysicsKinetics=d.Kinetics=void 0;var g=b(a("@babel/runtime/helpers/assertThisInitialized")),k=b(a("@babel/runtime/helpers/inherits")),h=b(a("@babel/runtime/helpers/possibleConstructorReturn")),
m=b(a("@babel/runtime/helpers/getPrototypeOf")),p=b(a("@babel/runtime/helpers/classCallCheck")),u=b(a("@babel/runtime/helpers/createClass")),n=b(a("@babel/runtime/helpers/defineProperty")),w=a("./canvas.js"),r=a("./constants.js"),v=function(){function a(b){var c=1<arguments.length&&void 0!==arguments[1]?arguments[1]:50,d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:50;(0,p.default)(this,a);(0,n.default)(this,"x",50);(0,n.default)(this,"y",50);(0,n.default)(this,"xdirection",1);(0,n.default)(this,
"ydirection",1);(0,n.default)(this,"angle",0);(0,n.default)(this,"origMotionFunction",void 0);(0,n.default)(this,"motionFunction",void 0);(0,n.default)(this,"last",this);b&&(this.origMotionFunction=b,this.motionFunction=b.bind(this));this.x=c;this.y=d}(0,u.default)(a,[{key:"clone",value:function(){return new a(this.origMotionFunction,this.x,this.y)}},{key:"computePhysics",value:function(){this.saveLast();void 0!==this.motionFunction&&this.motionFunction()}},{key:"reset",value:function(){this.y=this.x=
50;this.ydirection=this.xdirection=1;this.angle=0;this.saveLast()}},{key:"saveLast",value:function(){this.last=l({},this)}},{key:"setX",value:function(a){this.saveLast();this.x=a}},{key:"setY",value:function(a){this.saveLast();this.y=a}}]);return a}();d.Kinetics=v;a=function(a){function b(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:r.physics.gravity;(0,p.default)(this,b);var d=c.call(this);(0,n.default)((0,g.default)(d),"angle",0);(0,n.default)((0,g.default)(d),"x",w.cw/2);(0,n.default)((0,
g.default)(d),"y",w.ch/2);(0,n.default)((0,g.default)(d),"vx",0);(0,n.default)((0,g.default)(d),"vy",0);(0,n.default)((0,g.default)(d),"ax",0);(0,n.default)((0,g.default)(d),"ay",0);d.gravity=void 0!==a?a:r.physics.gravity;return d}(0,k.default)(b,a);var c=f(b);(0,u.default)(b,[{key:"clone",value:function(){return new b(this.gravity)}},{key:"computePhysics",value:function(){this.saveLast();this.ay+=this.gravity;this.ay*=r.physics.decayMotion;this.ax*=r.physics.decayMotion;this.vy+=this.ay;this.vx+=
this.ax;this.vy*=r.physics.decayMotion;this.vx*=r.physics.decayMotion;this.y+=this.vy;this.x+=this.vx}},{key:"applyAcceleration",value:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:1,d=3<arguments.length?arguments[3]:void 0;void 0===d&&(d=this.angle);this.saveLast();this.ax+=b*a*Math.sin(d);this.ay-=c*a*Math.cos(d)}},{key:"reset",value:function(){v.prototype.reset();this.vx=this.vy=this.ay=this.ax=0}}]);return b}(v);
d.PhysicsKinetics=a;a=function(a){function b(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:r.physics.gravity;(0,p.default)(this,b);var d=c.call(this);(0,n.default)((0,g.default)(d),"angle",0);(0,n.default)((0,g.default)(d),"x",w.cw/2);(0,n.default)((0,g.default)(d),"y",w.ch/2);(0,n.default)((0,g.default)(d),"vx",0);(0,n.default)((0,g.default)(d),"vy",0);(0,n.default)((0,g.default)(d),"ax",0);(0,n.default)((0,g.default)(d),"ay",0);d.gravity=void 0!==a?a:r.physics.gravity;return d}
(0,k.default)(b,a);var c=f(b);(0,u.default)(b,[{key:"clone",value:function(){return new b(this.gravity)}},{key:"computePhysics",value:function(){this.saveLast();this.ay+=this.gravity;this.vy+=this.ay;this.vx+=this.ax;this.y+=this.vy;this.x+=this.vx}},{key:"applyAcceleration",value:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:1,d=3<arguments.length?arguments[3]:void 0;void 0===d&&(d=this.angle);this.saveLast();this.ax+=
b*a*Math.sin(d);this.ay-=c*a*Math.cos(d)}},{key:"applyVelocity",value:function(a,b){void 0===b&&(b=this.angle);this.saveLast();this.vx+=a*Math.sin(b);this.vy-=a*Math.cos(b)}},{key:"reset",value:function(){v.prototype.reset();this.vx=this.vy=this.ay=this.ax=0}}]);return b}(v);d.PhysicsKineticsLand=a},{"./canvas.js":7,"./constants.js":10,"@babel/runtime/helpers/assertThisInitialized":21,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,
"@babel/runtime/helpers/getPrototypeOf":26,"@babel/runtime/helpers/inherits":27,"@babel/runtime/helpers/interopRequireDefault":28,"@babel/runtime/helpers/possibleConstructorReturn":32}],16:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,"__esModule",{value:!0});d.default=void 0;var f=b(a("@babel/runtime/helpers/classCallCheck")),c=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),l=b(a("./camera.js"));a=function(){function a(b){(0,
f.default)(this,a);(0,e.default)(this,"characters",[]);(0,e.default)(this,"cam",l.default);(0,e.default)(this,"keyboard",void 0);(0,e.default)(this,"sceneIndexToCamIndex",[]);(0,e.default)(this,"backgrounds",[]);(0,e.default)(this,"foregrounds",[]);this.cam=b}(0,c.default)(a,[{key:"initialize",value:function(){this.startingCondition&&this.startingCondition.bind(this)();this.cam.init();this.characters.forEach(function(a){a.init()});void 0!==this.keyboard&&this.keyboard.arm()}},{key:"dismantle",value:function(){var a=
this;void 0!==this.keyboard&&this.keyboard.disarm();this.characters.forEach(function(b){a.cam.dismantle();b.dismantle()});this.characters=[]}},{key:"nextStep",value:function(){this.characters.forEach(function(a){a.nextStep()});this.cam.renderFrame()}},{key:"register",value:function(a){a.init();this.characters.push(a);var b=this.characters.length-1;a=this.cam.registerChar(a);this.sceneIndexToCamIndex[b]=a;return b}},{key:"unregister",value:function(a){delete this.characters[a];this.cam.unregisterChar(this.sceneIndexToCamIndex[a])}},
{key:"hasCharacter",value:function(a){return a.find(function(b){return b===a})?!0:!1}},{key:"registerBG",value:function(a){this.cam.registerBG(a)}},{key:"registerFG",value:function(a){this.cam.registerFG(a)}}]);return a}();d.default=a},{"./camera.js":6,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/interopRequireDefault":28}],17:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");
Object.defineProperty(d,"__esModule",{value:!0});d.default=void 0;var f=b(a("@babel/runtime/helpers/classCallCheck")),c=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty"));a=function(){function a(){(0,f.default)(this,a);(0,e.default)(this,"curScene",void 0);(0,e.default)(this,"scenes",[]);return!0}(0,c.default)(a,[{key:"register",value:function(a,b){void 0===this.curScene&&(this.curScene=b,this.curScene.initialize());this.scenes.push({name:a,scene:b})}},{key:"gotoScene",
value:function(a){this.curScene.dismantle();var b=this.scenes.find(function(b){return b.name===a});void 0===b?console.log("No such Scene"):(this.curScene=b.scene,this.curScene.initialize())}},{key:"nextStep",value:function(){this.curScene&&this.curScene.nextStep()}},{key:"restart",value:function(){this.curScene.dismantle();this.curScene.initialize()}}]);return a}();d.default=a},{"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,
"@babel/runtime/helpers/interopRequireDefault":28}],18:[function(a,b,d){b=a("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(d,"__esModule",{value:!0});d.CompositeSpritesheet=d.default=void 0;var f=b(a("@babel/runtime/helpers/classCallCheck")),c=b(a("@babel/runtime/helpers/createClass")),e=b(a("@babel/runtime/helpers/defineProperty")),l=a("./constants.js"),g=a("./canvas.js");a=function(){function a(b){var c=this,d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,h=2<arguments.length&&
void 0!==arguments[2]?arguments[2]:{height:.5,width:.5};(0,f.default)(this,a);(0,e.default)(this,"image",void 0);(0,e.default)(this,"sheetwidth",void 0);(0,e.default)(this,"sheetheight",void 0);(0,e.default)(this,"cols",void 0);(0,e.default)(this,"spritewidth",void 0);(0,e.default)(this,"originFactor",void 0);(0,e.default)(this,"imageLoaded",!1);(0,e.default)(this,"draw",function(a,b){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:0,e=3<arguments.length&&void 0!==arguments[3]?arguments[3]:
1,f=4<arguments.length&&void 0!==arguments[4]?arguments[4]:1,h=5<arguments.length&&void 0!==arguments[5]?arguments[5]:void 0,l=6<arguments.length&&void 0!==arguments[6]?arguments[6]:void 0;void 0===h&&(h=c.image.width/c.cols);void 0===l&&(l=c.sheetheight);a=Math.floor(a);b=Math.floor(b);void 0!==c.image&&(g.cc.save(),g.cc.translate(a,b),0!==d&&g.cc.rotate(d),1===e&&1===f||g.cc.scale(e,f),g.cc.drawImage(c.image,c.curFrame*c.spritewidth-1,0,c.spritewidth,c.sheetheight,-h*c.originFactor.width,-l*c.originFactor.height,
h,l),g.cc.restore())});(0,e.default)(this,"curFrame",0);(0,e.default)(this,"animTimer",void 0);(0,e.default)(this,"alreadyAnimating",!1);(0,e.default)(this,"engaged",!1);(0,e.default)(this,"newFrame",function(){if(c.engaged){if(c.curFrame+1>=c.cols)return"done";++c.curFrame}});(0,e.default)(this,"resetFrame",function(){c.curFrame=0}.bind(this));void 0!==b&&(this.image=new Image,this.image.src=b,this.cols=d,this.curFrame=0,this.originFactor=h,this.image.onload=function(){c.sheetwidth=c.image.width;
c.sheetheight=c.image.height;c.spritewidth=c.sheetwidth/c.cols;c.imageLoaded=!0})}(0,c.default)(a,[{key:"clone",value:function(){if(this.imageLoaded){var b=new a;b.image=this.image;b.sheetheight=this.sheetheight;b.sheetwidth=this.sheetwidth;b.spritewidth=this.spritewidth;b.originFactor=this.originFactor;b.cols=this.cols;return b}return new a(this.location,this.cols,this.originFactor)}},{key:"engage",value:function(){this.engaged=!0;this.resetFrame()}},{key:"disengage",value:function(){this.engaged=
!1;this.resetFrame()}},{key:"startAnim",value:function(){var a=this,b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:l.frameRateMs;this.engaged&&!this.alreadyAnimating&&(this.animTimer=setInterval(function(){"done"===a.newFrame()&&a.resetFrame()},b),this.alreadyAnimating=!0)}},{key:"stopAnim",value:function(){clearInterval(this.animTimer);this.animTimer=void 0;this.resetFrame();this.alreadyAnimating=!1}},{key:"startAnimOneShot",value:function(){var a=this,b=0<arguments.length&&void 0!==arguments[0]?
arguments[0]:l.frameRateMs,c=1<arguments.length&&void 0!==arguments[1]?arguments[1]:void 0;if(this.engaged&&!this.alreadyAnimating){this.alreadyAnimating=!0;var d=setInterval(function(){"done"===a.newFrame()&&(window.clearInterval(d),a.alreadyAnimating=!1,c&&c())},b)}}},{key:"getSpriteWidth",value:function(){return this.image.width/this.cols}},{key:"getSpriteHeight",value:function(){return this.image.height}}]);return a}();d.default=a;a=function(){function a(){var b;(0,f.default)(this,a);(0,e.default)(this,
"sprites",[]);(b=this.sprites).push.apply(b,arguments)}(0,c.default)(a,[{key:"draw",value:function(){var a=arguments;this.sprites.forEach(function(b){return b.draw.apply(b,a)})}}]);return a}();d.CompositeSpritesheet=a},{"./canvas.js":7,"./constants.js":10,"@babel/runtime/helpers/classCallCheck":23,"@babel/runtime/helpers/createClass":24,"@babel/runtime/helpers/defineProperty":25,"@babel/runtime/helpers/interopRequireDefault":28}],19:[function(a,b,d){b.exports=function(a,b){if(null==b||b>a.length)b=
a.length;for(var c=0,d=Array(b);c<b;c++)d[c]=a[c];return d}},{}],20:[function(a,b,d){b.exports=function(a){if(Array.isArray(a))return a}},{}],21:[function(a,b,d){b.exports=function(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}},{}],22:[function(a,b,d){function f(a,b,d,f,k,h,m){try{var c=a[h](m),e=c.value}catch(n){d(n);return}c.done?b(e):Promise.resolve(e).then(f,k)}b.exports=function(a){return function(){var b=this,c=arguments;return new Promise(function(d,
e){function g(a){f(k,d,e,g,l,"next",a)}function l(a){f(k,d,e,g,l,"throw",a)}var k=a.apply(b,c);g(void 0)})}}},{}],23:[function(a,b,d){b.exports=function(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}},{}],24:[function(a,b,d){function f(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}b.exports=function(a,b,d){b&&f(a.prototype,b);d&&f(a,d);return a}},{}],25:[function(a,
b,d){b.exports=function(a,b,d){b in a?Object.defineProperty(a,b,{value:d,enumerable:!0,configurable:!0,writable:!0}):a[b]=d;return a}},{}],26:[function(a,b,d){function f(a){b.exports=f=Object.setPrototypeOf?Object.getPrototypeOf:function(a){return a.__proto__||Object.getPrototypeOf(a)};return f(a)}b.exports=f},{}],27:[function(a,b,d){var f=a("./setPrototypeOf");b.exports=function(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=
Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});b&&f(a,b)}},{"./setPrototypeOf":33}],28:[function(a,b,d){b.exports=function(a){return a&&a.__esModule?a:{"default":a}}},{}],29:[function(a,b,d){function f(){if("function"!==typeof WeakMap)return null;var a=new WeakMap;f=function(){return a};return a}var c=a("../helpers/typeof");b.exports=function(a){if(a&&a.__esModule)return a;if(null===a||"object"!==c(a)&&"function"!==typeof a)return{"default":a};var b=f();if(b&&b.has(a))return b.get(a);
var d={},e=Object.defineProperty&&Object.getOwnPropertyDescriptor,h;for(h in a)if(Object.prototype.hasOwnProperty.call(a,h)){var m=e?Object.getOwnPropertyDescriptor(a,h):null;m&&(m.get||m.set)?Object.defineProperty(d,h,m):d[h]=a[h]}d["default"]=a;b&&b.set(a,d);return d}},{"../helpers/typeof":35}],30:[function(a,b,d){b.exports=function(a,b){if("undefined"!==typeof Symbol&&Symbol.iterator in Object(a)){var d=[],c=!0,f=!1,k=void 0;try{for(var h=a[Symbol.iterator](),m;!(c=(m=h.next()).done)&&(d.push(m.value),
!b||d.length!==b);c=!0);}catch(p){f=!0,k=p}finally{try{if(!c&&null!=h["return"])h["return"]()}finally{if(f)throw k;}}return d}}},{}],31:[function(a,b,d){b.exports=function(){throw new TypeError("Invalid attempt to destructure non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}},{}],32:[function(a,b,d){var f=a("../helpers/typeof"),c=a("./assertThisInitialized");b.exports=function(a,b){return!b||"object"!==f(b)&&"function"!==typeof b?c(a):b}},
{"../helpers/typeof":35,"./assertThisInitialized":21}],33:[function(a,b,d){function f(a,d){b.exports=f=Object.setPrototypeOf||function(a,b){a.__proto__=b;return a};return f(a,d)}b.exports=f},{}],34:[function(a,b,d){var f=a("./arrayWithHoles"),c=a("./iterableToArrayLimit"),e=a("./unsupportedIterableToArray"),l=a("./nonIterableRest");b.exports=function(a,b){return f(a)||c(a,b)||e(a,b)||l()}},{"./arrayWithHoles":20,"./iterableToArrayLimit":30,"./nonIterableRest":31,"./unsupportedIterableToArray":36}],
35:[function(a,b,d){function f(a){"@babel/helpers - typeof";b.exports="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?f=function(a){return typeof a}:f=function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return f(a)}b.exports=f},{}],36:[function(a,b,d){var f=a("./arrayLikeToArray");b.exports=function(a,b){if(a){if("string"===typeof a)return f(a,b);var d=Object.prototype.toString.call(a).slice(8,-1);"Object"===d&&a.constructor&&
(d=a.constructor.name);if("Map"===d||"Set"===d)return Array.from(a);if("Arguments"===d||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(d))return f(a,b)}}},{"./arrayLikeToArray":19}],37:[function(a,b,d){b.exports=a("regenerator-runtime")},{"regenerator-runtime":38}],38:[function(a,b,d){a=function(a){function b(a,b,d,c){b=Object.create((b&&b.prototype instanceof f?b:f).prototype);c=new r(c||[]);b._invoke=p(a,d,c);return b}function d(a,b,d){try{return{type:"normal",arg:a.call(b,d)}}catch(M){return{type:"throw",
arg:M}}}function f(){}function g(){}function k(){}function h(a){["next","throw","return"].forEach(function(b){a[b]=function(a){return this._invoke(b,a)}})}function m(a,b){function c(e,f,g,h){e=d(a[e],a,f);if("throw"===e.type)h(e.arg);else{var D=e.arg;return(e=D.value)&&"object"===typeof e&&C.call(e,"__await")?b.resolve(e.__await).then(function(a){c("next",a,g,h)},function(a){c("throw",a,g,h)}):b.resolve(e).then(function(a){D.value=a;g(D)},function(a){return c("throw",a,g,h)})}}var e;this._invoke=
function(a,d){function f(){return new b(function(b,e){c(a,d,b,e)})}return e=e?e.then(f,f):f()}}function p(a,b,c){var e=I;return function(f,g){if(e===J)throw Error("Generator is already running");if(e===F){if("throw"===f)throw g;return B()}c.method=f;for(c.arg=g;;){if(f=c.delegate)if(f=u(f,c)){if(f===t)continue;return f}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(e===I)throw e=F,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);e=J;f=d(a,
b,c);if("normal"===f.type){e=c.done?F:L;if(f.arg===t)continue;return{value:f.arg,done:c.done}}"throw"===f.type&&(e=F,c.method="throw",c.arg=f.arg)}}}function u(a,b){var c=a.iterator[b.method];if(c===x){b.delegate=null;if("throw"===b.method){if(a.iterator["return"]&&(b.method="return",b.arg=x,u(a,b),"throw"===b.method))return t;b.method="throw";b.arg=new TypeError("The iterator does not provide a 'throw' method")}return t}c=d(c,a.iterator,b.arg);if("throw"===c.type)return b.method="throw",b.arg=c.arg,
b.delegate=null,t;c=c.arg;if(!c)return b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,t;if(c.done)b[a.resultName]=c.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=x);else return c;b.delegate=null;return t}function n(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function w(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function r(a){this.tryEntries=
[{tryLoc:"root"}];a.forEach(n,this);this.reset(!0)}function v(a){if(a){var b=a[G];if(b)return b.call(a);if("function"===typeof a.next)return a;if(!isNaN(a.length)){var c=-1;b=function q(){for(;++c<a.length;)if(C.call(a,c))return q.value=a[c],q.done=!1,q;q.value=x;q.done=!0;return q};return b.next=b}}return{next:B}}function B(){return{value:x,done:!0}}var K=Object.prototype,C=K.hasOwnProperty,x,A="function"===typeof Symbol?Symbol:{},G=A.iterator||"@@iterator",O=A.asyncIterator||"@@asyncIterator",H=
A.toStringTag||"@@toStringTag";a.wrap=b;var I="suspendedStart",L="suspendedYield",J="executing",F="completed",t={};A={};A[G]=function(){return this};var y=Object.getPrototypeOf;(y=y&&y(y(v([]))))&&y!==K&&C.call(y,G)&&(A=y);var z=k.prototype=f.prototype=Object.create(A);g.prototype=z.constructor=k;k.constructor=g;k[H]=g.displayName="GeneratorFunction";a.isGeneratorFunction=function(a){return(a="function"===typeof a&&a.constructor)?a===g||"GeneratorFunction"===(a.displayName||a.name):!1};a.mark=function(a){Object.setPrototypeOf?
Object.setPrototypeOf(a,k):(a.__proto__=k,H in a||(a[H]="GeneratorFunction"));a.prototype=Object.create(z);return a};a.awrap=function(a){return{__await:a}};h(m.prototype);m.prototype[O]=function(){return this};a.AsyncIterator=m;a.async=function(c,d,e,f,g){void 0===g&&(g=Promise);var h=new m(b(c,d,e,f),g);return a.isGeneratorFunction(d)?h:h.next().then(function(a){return a.done?a.value:h.next()})};h(z);z[H]="Generator";z[G]=function(){return this};z.toString=function(){return"[object Generator]"};
a.keys=function(a){var b=[],c;for(c in a)b.push(c);b.reverse();return function q(){for(;b.length;){var c=b.pop();if(c in a)return q.value=c,q.done=!1,q}q.done=!0;return q}};a.values=v;r.prototype={constructor:r,reset:function(a){this.next=this.prev=0;this.sent=this._sent=x;this.done=!1;this.delegate=null;this.method="next";this.arg=x;this.tryEntries.forEach(w);if(!a)for(var b in this)"t"===b.charAt(0)&&C.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=x)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;
if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,d){f.type="throw";f.arg=a;c.next=b;d&&(c.method="next",c.arg=x);return!!d}if(this.done)throw a;for(var c=this,d=this.tryEntries.length-1;0<=d;--d){var e=this.tryEntries[d],f=e.completion;if("root"===e.tryLoc)return b("end");if(e.tryLoc<=this.prev){var g=C.call(e,"catchLoc"),h=C.call(e,"finallyLoc");if(g&&h){if(this.prev<e.catchLoc)return b(e.catchLoc,!0);if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else if(g){if(this.prev<
e.catchLoc)return b(e.catchLoc,!0)}else if(h){if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(a,b){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];if(d.tryLoc<=this.prev&&C.call(d,"finallyLoc")&&this.prev<d.finallyLoc){var e=d;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=b&&b<=e.finallyLoc&&(e=null);c=e?e.completion:{};c.type=a;c.arg=b;return e?(this.method="next",this.next=e.finallyLoc,t):
this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b);return t},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),w(c),t}},"catch":function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];
if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var d=a.arg;w(c)}return d}}throw Error("illegal catch attempt");},delegateYield:function(a,b,c){this.delegate={iterator:v(a),resultName:b,nextLoc:c};"next"===this.method&&(this.arg=x);return t}};return a}("object"===typeof b?b.exports:{});try{regeneratorRuntime=a}catch(f){Function("r","regeneratorRuntime = r")(a)}},{}]},{},[2]);
